-- MySQL Script generated by MySQL Workbench
-- Sat Dec 15 13:47:28 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `caritascolima` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `caritascolima` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `caritascolima` ;

-- -----------------------------------------------------
-- Table `Instituciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Instituciones` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Instituciones` (
  `idInstituciones` INT NOT NULL AUTO_INCREMENT,
  `nombreInstitucion` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`idInstituciones`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `idInstituciones_UNIQUE` ON `Instituciones` (`idInstituciones` ASC);

SHOW WARNINGS;
CREATE UNIQUE INDEX `nombreInstitucion_UNIQUE` ON `Instituciones` (`nombreInstitucion` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Roles` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Roles` (
  `idRoles` INT NOT NULL AUTO_INCREMENT,
  `nombreRol` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`idRoles`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Usuarios` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Usuarios` (
  `idUsuarios` VARCHAR(30) NOT NULL,
  `Contrasena` VARCHAR(250) NOT NULL,
  `idRol` INT NOT NULL,
  PRIMARY KEY (`idUsuarios`),
  CONSTRAINT `FK_idRol_Usuarios`
    FOREIGN KEY (`idRol`)
    REFERENCES `Roles` (`idRoles`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `idUsuarios_UNIQUE` ON `Usuarios` (`idUsuarios` ASC);

SHOW WARNINGS;
CREATE INDEX `idRol_idx` ON `Usuarios` (`idRol` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Actividades`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Actividades` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Actividades` (
  `idActividades` INT NOT NULL AUTO_INCREMENT,
  `idInstitucion` INT NOT NULL,
  `fechaActividad` DATE NOT NULL,
  `asistentesActividad` INT NOT NULL,
  `despensasActividad` INT NOT NULL,
  `actividadExtra` VARCHAR(1000) NULL,
  `institucionUno` INT NOT NULL,
  `institucionDos` INT NULL,
  `voluntarioActividad` VARCHAR(250) NULL,
  `actividadUno` VARCHAR(1000) NOT NULL,
  `actividadDos` VARCHAR(1000) NULL,
  `idRol` INT NOT NULL,
  PRIMARY KEY (`idActividades`),
  CONSTRAINT `FK_idInstitucionActividades`
    FOREIGN KEY (`idInstitucion`)
    REFERENCES `Instituciones` (`idInstituciones`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `FK_idRolActividades`
    FOREIGN KEY (`idRol`)
    REFERENCES `Roles` (`idRoles`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `idActividades_UNIQUE` ON `Actividades` (`idActividades` ASC);

SHOW WARNINGS;
CREATE INDEX `FK_idInstitucionActividades_idx` ON `Actividades` (`idInstitucion` ASC);

SHOW WARNINGS;
CREATE INDEX `FK_idRolActividades_idx` ON `Actividades` (`idRol` ASC);

SHOW WARNINGS;
CREATE INDEX `FK_institucionUnoActividades_idx` ON `Actividades` (`institucionUno` ASC, `institucionDos` ASC);

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO Roles VALUES (null, 'Administrador');
INSERT INTO Roles VALUES (null, 'Niños');
INSERT INTO Roles VALUES (null, 'Adultos');
